version: '3.8'

networks:
  send_email_network:
    driver: bridge

volumes:
  rabbitmqdata:
    driver: local

services:
  # =================================================================
  # SEND EMAIL SERVICE
  # =================================================================

  # Conteneur PHP-FPM pour le service d'envoi d'e-mails
  send_email_app:
    build:
      context: .
      dockerfile: Dockerfile
    image: send-email-service
    container_name: send-email-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - send_email_network
    depends_on:
      - rabbitmq
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:JeJcjYE9eJf61A2GRy8c4MuBwKAUUFlHQ3VcINXlLNY=
      - APP_URL=http://localhost:8081
      - QUEUE_CONNECTION=rabbitmq
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=admin
      - RABBITMQ_PASSWORD=admin
      - RABBITMQ_VHOST=/
      - CACHE_DRIVER=file
      - SESSION_DRIVER=file
      - MAIL_MAILER=smtp
      - MAIL_HOST=mailhog
      - MAIL_PORT=1025
      - MAIL_USERNAME=null
      - MAIL_PASSWORD=null
      - MAIL_ENCRYPTION=null
      - MAIL_FROM_ADDRESS=noreply@sendmail.local
      - MAIL_FROM_NAME=SendEmail Service

  # Conteneur Nginx pour le service d'envoi d'e-mails
  send_email_webserver:
    image: nginx:alpine
    container_name: send-email-webserver
    restart: unless-stopped
    ports:
      - "8081:80"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - send_email_network
    depends_on:
      - send_email_app

  # =================================================================
  # INFRASTRUCTURE SERVICES
  # =================================================================

  # File d'attente de messages
  rabbitmq:
    image: rabbitmq:3-management
    container_name: send-email-rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - "15673:15672"  # Port différent pour éviter les conflits
      - "5673:5672"    # Port différent pour éviter les conflits
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    networks:
      - send_email_network